### ISSUE TITLE
Protect VIA ports with current limit resistors

### ISSUE THREAD

**Issue by rl000** [picocomputer/schematic#1]
Hello,

W65C22S could be damage by short to the power rails and IO pins or between IO pins. Previous versions of the device have build in protection resistors, however W65C22S doesn't have protection (please see datasheet 5.5).

It will be nice to have protection resistors on PCB in serials with ports output and pin header with value about 180 Om.

Regards,
Roman

**Comment by rumbledethumps** [comment]
The current limiting resistors were almost certainly removed because circuit designers asked for them to be removed. I'm not putting them back. This violates the principle of least surprise.
